[package]
name = "flight-network-planner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1.0.145", features = ["derive"] }
serde_yaml = "^0.9.13"
reqwest = { version = "^0.11.12", features = ["blocking"] }
log = "^0.4.17"
pretty_env_logger = "^0.4.0"
clap = { version = "^4.0.10", features = ["derive"] }
cached = "^0.39.0"
anyhow = { version = "^1.0.65", features = ["backtrace"] }
counter = "^0.5.6"
itertools = "^0.10.5"
regex = "^1.6.0"
csv = "^1.1.6"
