[package]
name = "flight-network-planner"
version = "1.1.0"
edition = "2021"
description = "Minecart Rapid Transit Flight Network Planner for airlines, made by __7d"
authors = ["__7d"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1.0.164", features = ["derive"] }
serde_yaml = "^0.9.22"
reqwest = { version = "^0.11.18", features = ["blocking"] }
log = "^0.4.19"
pretty_env_logger = "^0.5.0"
clap = { version = "^4.3.8", features = ["derive"] }
clap_complete = "^4.3.1"
clap_complete_fig = "^4.3.1"
cached = "^0.46.0"
anyhow = { version = "^1.0.71", features = ["backtrace"] }
counter = "^0.5.7"
itertools = "^0.11.0"
regex = "^1.8.4"
csv = "^1.2.2"
smol_str = { version = "^0.2.0", features = ["serde"] }

[profile.release]
opt-level = 3
lto = true

[profile.dev]
opt-level = 3
