[package]
name = "flight-network-planner"
version = "1.0.0"
edition = "2021"
description = "Minecart Rapid Transit Flight Network Planner for airlines, made by __7d"
authors = ["__7d"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1.0.145", features = ["derive"] }
serde_yaml = "^0.9.13"
reqwest = { version = "^0.11.12", features = ["blocking"] }
log = "^0.4.17"
pretty_env_logger = "^0.4.0"
clap = { version = "^4.0.10", features = ["derive"] }
clap_complete = "^4.0.1"
clap_complete_fig = "^4.0.0-rc.1"
cached = "^0.39.0"
anyhow = { version = "^1.0.65", features = ["backtrace"] }
counter = "^0.5.6"
itertools = "^0.10.5"
regex = "^1.6.0"
csv = "^1.1.6"
smol_str = "^0.1.23"

[profile.release]
opt-level = 3
lto = true

[profile.dev]
opt-level = 3