[package]
name = "flight-network-planner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "~1.0.139", features = ["derive"] }
serde_yaml = "~0.9.0"
reqwest = { version = "~0.11.11", features = ["blocking", "json"] }
log = "~0.4.17"
clap = { version = "~3.2.15", features = ["derive"] }