[package]
name = "flight-network-planner"
version = "1.1.0"
edition = "2021"
description = "Minecart Rapid Transit Flight Network Planner for airlines, made by __7d"
authors = ["__7d"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1.0.154", features = ["derive"] }
serde_yaml = "^0.9.19"
reqwest = { version = "^0.11.14", features = ["blocking"] }
log = "^0.4.17"
pretty_env_logger = "^0.4.0"
clap = { version = "^4.1.8", features = ["derive"] }
clap_complete = "^4.1.4"
clap_complete_fig = "^4.1.1"
cached = "^0.42.0"
anyhow = { version = "^1.0.69", features = ["backtrace"] }
counter = "^0.5.7"
itertools = "^0.10.5"
regex = "^1.7.1"
csv = "^1.2.1"
smol_str = "^0.1.24"

[profile.release]
opt-level = 3
lto = true

[profile.dev]
opt-level = 3
