[package]
name = "flight-network-planner"
version = "1.1.0"
edition = "2021"
description = "Minecart Rapid Transit Flight Network Planner for airlines, made by __7d"
authors = ["__7d"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1.0.162", features = ["derive"] }
serde_yaml = "^0.9.21"
reqwest = { version = "^0.11.17", features = ["blocking"] }
log = "^0.4.17"
pretty_env_logger = "^0.5.0"
clap = { version = "^4.2.7", features = ["derive"] }
clap_complete = "^4.2.1"
clap_complete_fig = "^4.2.0"
cached = "^0.43.0"
anyhow = { version = "^1.0.71", features = ["backtrace"] }
counter = "^0.5.7"
itertools = "^0.10.5"
regex = "^1.8.1"
csv = "^1.2.1"
smol_str = "^0.2.0"

[profile.release]
opt-level = 3
lto = true

[profile.dev]
opt-level = 3
