[package]
name = "flight-network-planner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "~1.0.139", features = ["derive"] }
serde_yaml = "~0.9.0"
reqwest = { version = "~0.11.11", features = ["blocking", "json"] }
log = "~0.4.17"
pretty_env_logger = "~0.4.0"
clap = { version = "~3.2.15", features = ["derive"] }
cached = "~0.38.0"
anyhow = { version = "~1.0.58", features = ["backtrace"] }
counter = "~0.5.6"
itertools = "~0.10.3"
regex = "~1.6.0"
csv = "~1.1.6"