# MRT Flight Network Planner Configuration file

# == General ==
# airline_name: The name of the airline
# airline_code: The two-letter code that is prefixed to all flight numbers
airline_name: Astrella
airline_code: ""

# == Handling existing flights ==
# Flight data is pulled from the MRT Transit sheet.
# ignored_airlines: The airlines to be ignored on the sheet (default: the value in airline_name)
ignored_airlines:
  ["Kaloro Air", "FlyLumeva", "FlySubway", "MRTHS Air", "Astrella"]

# == Airports ==
# hubs: A list of hubs for your airline. (default: all airports with at least the number of gates in hub_threshold)
# hub_threshold: The minimum number of gates for an airport to be considered a hub, if hubs is empty
hubs: [CIA, PCE, MWT, LAR, SEG, VDA, AIX, NPR]
hub_threshold: 5

# == Flight naming scheme ==
# For range_XXX values, give ranges as [[min1, max1], [min2, max2], ...]
# range_h2h: The range of flight numbers for hub-to-hub flights
# range_n2n: The range of flight numbers for non-hub-to-non-hub flights
# range_h2n: The range of flight numbers for hub-to-non-hub flights
#   XXX: [...]: XXX is the hub's airport code
# both_dir_same_num: Whether flights use the same number for both directions
range_h2h: [[1, 100]]
range_n2n: [[9001, 9999]]
range_h2n:
  CIA: [[101, 300]]
  PCE: [[301, 500]]
  MWT: [[501, 700]]
  LAR: [[701, 900]]
  SEG: [[901, 1100]]
  VDA: [[1101, 1300]]
  AIX: [[1301, 1500]]
  NPR: [[1501, 1700]]
both_dir_same_num: false

# == Gates ==
# If both gate_json and gates are provided, gate_json will be picked first
# gate_json: The JSON file of all gates at each airport
# gates: A list of all the gates in the airport
#   XXX: XXX is the hub's airport code
#   - code: The code of the gate
#     size: The size of the gate
gate_file: gates.txt
gates: {}

# == Warp limits ==
# hard_max_hub: The hard maximum number of warps in a plane for hub airports. No plane will go past this number of warps.
# hard_max_hub: The hard maximum number of warps in a plane for non-hub airports. No plane will go past this number of warps.
# max_h2n: The maximum number of h2n warps in a plane. Applies to non-hubs only.
# max_n2n: The maximum number of n2n warps in a plane.
hard_max_hub: 5
hard_max_nonhub: 4
max_h2h: 1
max_h2n_hub: 5
max_h2n_nonhub: 4
max_n2n: 2

# == Flight restrictions ==
# restricted_between: A list of set of airports that cannot be flown between one another.
# restricted_to: A mapping of airports to a list of destinations that are not able to be flown to.
# preferred_between: A list of set of airports that are preferred to be flown between one another.
# preferred_to: A mapping of airports to a list of destinations that are preferred to be flown to.
restricted_between:
  [
    [VDA, DFM, DPH, GSM, WMI, DJE, DBI],
    [LFA, LAR],
    [MSA, MPI],
    [TCB, TSA, TSN],
    [ACA, EIA],
    [MFM, MWK, MWT, MWL],
    [PXA, EEA, PXL],
  ]
restricted_to:
  MWT: [DFM, DPH, VDA, DJE, WMA, RIV, MAX, MMA, LAR, VFW, SEG, RAA]
  PIA: [MWT]
  PCA: [MWT]
  MBI: [MWT]
  MWK: [MWT]
  PXA: [EEA, PXL]
  NPR: [ZRZ]
  GEP: [PFR, YNB, NPR, CAR, GLA]
  ERZ: [NPR]
preferred_between: [[KEK, KZH]]
preferred_to:
  PCE: [SVS, MWT]
  PCA: [PCE, RED, PIA, EIA]
  SHI: [CIA, KEK, TOU]
  GOD: [CIA, MWT, AIX, NPR]
  WCC: [CIA, AIX, MWT, EIA]
  EMI: [PCE, MWT]
no_dupes: [WMA, CAP, DHA, PCE, WCC]

# == Airport restrictions ==
# gate_restrictions_allowed: A mapping of airports to a mapping of gates to a list of destinations that are only able to be flown to from the gate.
# gate_restrictions_not_allowed: A mapping of airports to a mapping of gates to a list of destinations that are not able to be flown to from the gate.
gate_allowed_dests:
  PCE:
    B1: &pce [SVS, RSA, RSN, GSZ, RSZ, SKA, RED, VIC, RVC, PSD, COA]
    B2: *pce
  TCB:
    A2: [OCD, TSN, TCB, TSA, RAV, HND, HGW, GBE, STS]

gate_denied_dests:
  PCE:
    A1: *pce
    A2: *pce
    A3: *pce
    A4: *pce
    A5: *pce
    A6: *pce
    A7: *pce
    A8: *pce
    A9: *pce
max_dests_per_gate:
  PIA: 2
