# MRT Flight Network Planner Configuration file

# == General ==
# airline_name: The name of the airline
# airline_code: The two-letter code that is prefixed to all flight numbers
airline_name: Astrella
airline_code: ""

# == Handling existing flights ==
# Flight data is pulled from the MRT Transit sheet.
# ignored_airlines: The airlines to be ignored on the sheet (default: the value in airline_name)
ignored_airlines: ["Kaloro Air", "FlyLumeva", "FlySubway", "MRTHS Air"]

# == Airports ==
# hubs: A list of hubs for your airline. (default: all airports with at least the number of gates in hub_threshold)
# hub_threshold: The minimum number of gates for an airport to be considered a hub, if hubs is empty
hubs: [PCE, CIA, LAR, EEA, TBI, FYI, KTI, VDA, WMI]
hub_threshold: 5

# == Flight naming scheme ==
# For range_XXX values, give ranges as [[min1, max1], [min2, max2], ...]
# range_h2h: The range of flight numbers for hub-to-hub flights
# range_n2n: The range of flight numbers for nonhub-to-nonhub flights
# range_h2n: The range of flight numbers for hub-to-nonhub flights
#   XXX: [...]: XXX is the hub's airport code
# both_dir_same_num: Whether flights use the same number for both directions
range_h2h: [[1, 100]]
range_n2n: [[1001, 1100]]
range_h2n:
  LAR: [[101, 200]]
  EEA: [[201, 300]]
  TBI: [[301, 400]]
  CIA: [[401, 500]]
  FYI: [[501, 600]]
  KTI: [[601, 700]]
  VDA: [[701, 800]]
  WMI: [[801, 900]]
  PCE: [[901, 1000]]
both_dir_same_num: true

# == Gates ==
# If both gate_json and gates are provided, gate_json will be picked first
# gate_json: The JSON file of all gates at each airport
# gates: A list of all the gates in the airport
#   XXX: XXX is the hub's airport code
#   - code: The code of the gate
#     size: The size of the gate
gate_json:
gates:
  PCE:
    - code: A1
      size: S
    - code: A2
      size: S
  AIX:
    - code: B1
      size: S
    - code: B2
      size: M
  TKX:
    - code: C1
      size: M
    - code: C2
      size: S
  NMW:
    - code: D1
      size: M
      
# == Warp limits ==
# hard_max: The hard maximum number of warps in a plane. No plane will go past this number of warps.
# max_h2n: The maximum number of h2n warps in a plane. Applies to nonhubs only.
# max_n2n: The maximum number of n2n warps in a plane.
hard_max: 4
max_h2n: 4
max_n2n: 1